name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./DeliBuddy
      NAVER_MAP_APIKEY_ID: ${{ secrets.NAVER_MAP_APIKEY_ID }}
      NAVER_MAP_APIKEY_SECRET: ${{ secrets.NAVER_MAP_APIKEY_SECRET }}

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Access NAVER_MAP_APIKEY_ID
      run: echo NAVER_MAP_APIKEY_ID=\"$NAVER_MAP_APIKEY_ID\" > ./local.properties
      working-directory: ${{ env.working-directory }}
      
    - name: Access NAVER_MAP_APIKEY_SECRET
      run: echo NAVER_MAP_APIKEY_SECRET=\"$NAVER_MAP_APIKEY_SECRET\" >> ./local.properties
      working-directory: ${{ env.working-directory }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{ env.working-directory }}
