name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      NAVER_MAP_APIKEY_ID: ${{ secrets.NAVER_MAP_APIKEY_ID }}
      NAVER_MAP_APIKEY_SECRET: ${{ secrets.NAVER_MAP_APIKEY_SECRET }}

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Access NAVER_MAP_APIKEY_ID
      run: echo NAVER_MAP_APIKEY_ID=\"$NAVER_MAP_APIKEY_ID\" > ./local.properties
      
    - name: Access NAVER_MAP_APIKEY_SECRET3
      run: echo NAVER_MAP_APIKEY_SECRET=\"$NAVER_MAP_APIKEY_SECRET\" > ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
